server:
  port: 3344
spring:
  application:
    name: cloud-config-center # 注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/colinCalvin/SpringCloud-Config.git  # github上的git仓库链接
          # 搜索目录
          search-paths:
            - SpringCloud-Config
      # 读取分支
      label: master
  # 添加rabbitmq相关配置
  rabbitmq:
    host: 192.168.48.130
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

# rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
