server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root

mybatis:
  # 所有Entity别名类所在包
  type-aliases-package: com.cloud.cloudapicommons.entities
  # 配置文件所在位置
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    # 表示是否将自己注册进Eureka注册中心
    register-with-eureka: true
    # 是否从Eureka注册中心拉取已经注册的服务信息
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
