server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root

mybatis:
  # 所有Entity别名类所在包
  type-aliases-package: com.cloud.springcloud.entities
  # 配置文件所在位置
  mapper-locations: classpath:mapper/*.xml